# What modules display
set -g @catppuccin_date_time_text '%d.%m %H:%M'
##### Status line (set AFTER theme load) #####
#set -g @catppuccin_window_left_separator ""
#set -g @catppuccin_window_right_separator " "
#set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
#set -g @catppuccin_status_left_separator  " "
#set -g @catppuccin_status_right_separator " "
#set -g @catppuccin_status_connect_separator "no"

#Left
set -g status-left-length 100
set -g status-left ""
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_connect_separator "no"

#Right
set -g status-right-length 140
set -g status-right "  #{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -agF status-right " #{E:@catppuccin_status_cpu}"
set -agF status-right " #{E:@catppuccin_status_battery}"
#set -ag status-right "#{E:@catppuccin_status_uptime}"
set -ag  status-right " #{E:@catppuccin_status_date_time}"
set-option -g status-position top


