# vim: ft=tmux
# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
##### SessionX (tmux-sessionx) #####
set -g @plugin 'omerxx/tmux-sessionx'


# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/tmux/catppuccin.tmux

# Initialize TPM (this runs catppuccin with the settings above)
source-file ~/.config/tmux/catppuccin-theme.conf

# Plugin Configuration
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'off'
set -g @continuum-save-interval '1'


set -g @resurrect-dir "~/.config/tmux/resurrect"


set-environment -gF TMUX_PLUGIN_MANAGER_PATH '#{HOME}/.config/tmux/plugins/'
if 'test ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm"' {
  run 'mkdir -p "${TMUX_PLUGIN_MANAGER_PATH}"'
  run 'git clone https://github.com/tmux-plugins/tpm "${TMUX_PLUGIN_MANAGER_PATH}/tpm"'
  run '"${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins"'
}



run '~/.config/tmux/plugins/tpm/tpm'
